### ISSUE TITLE
Migrate to buzzfeed/sso from bitly/oauth2_proxy which is not maintained

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/sso-operator#13]
The bitly/oauth2_proxy does not seems to be maintained anymore. It will be archived end of September https://github.com/bitly/oauth2_proxy/issues/628.

https://github.com/buzzfeed/sso/blob/master/docs/quickstart.md

**Comment by apriendeau** [comment]
For clarification: it will be available but it will be read-only.

**Comment by ccojocar** [comment]
This is not required anymore since now `oauth2_proxy` is maintained again. 
https://github.com/pusher/oauth2_proxy
