### ISSUE TITLE
jx create addon sso --set="rbac.create=false" does not change value

### ISSUE THREAD

**Issue by thegalah** [jenkins-x/sso-operator#16]
Running `jx create addon sso --set="rbac.create=false"` does not set the correct value and will fail on the cert-manager step.

`error: ensuring cert-manager is installed: CertManager deployment failed: failed to run 'helm upgrade --namespace cert-manager --install --force --timeout 6000 --version  --set rbac.create=true --set ingressShim.extraArgs='{--default-issuer-name=letsencrypt-staging,--default-issuer-kind=Issuer}' cert-manager stable/cert-manager'`

The expected behaviour is that the value `rbac.create` should be true as specified according to the `jx create addon --help` command:
```
  -s, --set='': The chart set values (can specify multiple or separate values with commas: key1=val1,key2=val2)


```

**Comment by ccojocar** [comment]
@thegalah What's the reason for tuning RBAC off? This value is not supported by the `sso-opeator` chat.

**Comment by thegalah** [comment]
Ah appears to be a misunderstanding on my part. Closing
