### ISSUE TITLE
Support ingresses annotations and default config

### ISSUE THREAD

**Issue by aslafy-z** [jenkins-x/sso-operator#20]
I'd love to be able to add SSO to a Ingress only by adding annotations in my ingresses. It could then use the config I saved in the initial `sso-operator` deployment as default to create a SSO resource (or handle it directly).

I'd love to try to build the integration if it fits anyone.

WDYT?

**Comment by ccojocar** [comment]
The idea is to use the sso proxy (provisioned by the `sso-operator`) between the service and the ingress resource, in this way all the requests are intercepted by the sso proxy. The ingress resource is created automatically by the expose controller when the sso proxy is provisioned. 

I am not sure if it is possible to archive something similar by placing the sso proxy in front of the ingress. Is this what you are asking for?
